

# Setting user
#spring.security.user.name=admin
#spring.security.user.password=admin123
#spring.security.user.role=ADMIN


server:
  port: 9080
  servlet:
    context-path: "/backend"


spring:
  datasource:
    url: jdbc:mysql://mysql.mysql-operator.svc.cluster.local/reef-forge-database
    username: root
    password: veryStrongPassword@7410


  # Logging configs
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
      use_sql_comments: true

    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply@reef-forge.uk
    password: "utal pafk nbeq gjpk"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org:
      hibernate:
        SQL:
          INFO
    com:
      zaxxer:
        hikari: DEBUG