

# Setting user
#spring.security.user.name=admin
#spring.security.user.password=admin123
#spring.security.user.role=ADMIN


server:
  port: 9080
  servlet:
    context-path: "/backend"



#

#spring:
#  datasource:
#    url: ${spring.datasource.url}
#    username: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/himalayanfresh_coffee
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
#      use_sql_comments: true
#    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: gcp2.sujangurung@gmail.com
    password: "jhyt auqh icem hvnw"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org:
      hibernate:
        SQL:
          INFO
    com:
      zaxxer:
        hikari: DEBUG



# Logging configs
#logging.level.com.better.backend_app = TRACE
#logging.pattern.console=%d [%level] %c{1.} [%t] %m%n
#logging.file = appLog.log
#logging.pattern.file=%d [%level] %c{1.} %m%n



#logging.level.org.springframework.security=DEBUG

