apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name}}-deployment
  namespace: {{ .Values.namespace.name}}
  labels:
    app: {{ .Values.app.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name}}
      annotations:
        sidecar.istio.io/inject: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "reef-forge-fe-policy"  # Vault role mapped to ServiceAccount
        vault.hashicorp.com/agent-inject-secret-gcs.json: "kv/gcs_credentials"
        vault.hashicorp.com/agent-inject-template-gcs.json: |
        {
          "type": "{{ with secret`{{.Data.data.type  }}`}}{{ end }}",
          "project_id": "{{ with secret`{{ .Data.data.project_id  }}`}}{{ end }}",
          "private_key_id": "{{ with secret`{{ .Data.data.private_key_id  }}`}}{{ end }}",
          "private_key": "{{ with secret`{{ .Data.data.private_key  }}`}}{{ end }}",
          "client_email": "{{ with secret`{{ .Data.data.client_email  }}`}}{{ end }}",
          "client_id": "{{ with secret`{{ .Data.data.client_id  }}`}}{{ end }}",
          "auth_uri": "{{ with secret`{{ .Data.data.auth_uri  }}`}}{{ end }}",
          "token_uri": "{{ with secret`{{ .Data.data.token_uri  }}`}}{{ end }}",
          "auth_provider_x509_cert_url": "{{ with secret`{{ .Data.data.auth_provider_x509_cert_url  }}`}}{{ end }}",
          "client_x509_cert_url": "{{ with secret`{{ .Data.data.client_x509_cert_url  }}`}}{{ end }}",
          "universe_domain": "{{ with secret `{{ .Data.data.universe_domain  }}`}}{{ end }}"
        }
        vault.hashicorp.com/agent-inject-file-gcs.json: "omega-vigil-413814-158bf59a2903.json"

    spec:
      serviceAccountName: { { .Values.app.name } }-sa # Use the service account
      containers:
      - name: {{ .Values.app.name}}
        image: {{ .Values.app.image.name}}:{{.Values.app.image.tag}}
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        env:
          - name: JAVA_OPTS
            value: "-Dspring.profiles.active=dev"

